server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/alcoholic
    username: root
    password: root

  #JPA 설정
  jpa:
    show-sql: true


