server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/alcoholic
    username: root
    password: root

  #JPA 설정
  jpa:
    show-sql: true

#토큰 발급 만료시간 3시간으로 설정
app:
  auth:
    tokenSecret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    tokenExpiry: 10800000

